### ISSUE TITLE
The docs could be more helpful

### ISSUE THREAD

**Issue by Pumpapa** [gothinkster/elixir-phoenix-realworld-example-app#42]
Dependencies are Elixir, Phoenix, PostgreSQL, but Phoenix depends on Postgresql so the order isn't right
The Phoenix docs say to install `mix local.hex` but that doesn't work
I skip that and continue on your instructions, and `mix deps.get` offers to install hex. Goodie.
But then: `mix ecto.create` installs a lot but fails at
```
...
14:04:16.964 [error] GenServer #PID<0.7212.0> terminating
** (Postgrex.Error) FATAL 28P01 (invalid_password): password authentication failed for user "postgres"
    (db_connection 1.1.3) lib/db_connection/connection.ex:163: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for RealWorld.Repo couldn't be created: FATAL 28P01 (invalid_password): password authentication failed for user "postgres"
```
Presumably I should have created the `postgres` user, but this isn't mentioned anywhere.
But I rarely use postgres, so I wouldn't know where to begin

**Comment by bartvanderwal** [comment]
As mentioned in my issue #45 the default username for postgres on macos is your macos username.

If you're running windows, this might be different, check the postgres docs. I DID get a slightly different error message, so perhaps your username is correct, but besides changing the `username`, you could also try changing your `password` in the `config.exs` file. For instance set it to empty as I did (which [is default on other systems as well](https://chartio.com/resources/tutorials/how-to-set-the-default-user-password-in-postgresql/). Or — of course — to the password you entered on install — if any.
